project:
  type: website

website:
  title: "NC Data Labs"
  google-analytics: G-QP16Z1MVTP 
  site-url: https://www.ncdatalabs.com
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Services
        href: services.qmd
      - text: Selected Work
        href: selected_work.qmd
      - text: Contact
        href: contact.qmd
      - text: About
        href: about.qmd
      - text: Blog
        href: ./blog/index.qmd

format:
  html:
    theme:
      light: styles/custom-theme.scss
    css: styles/styles.css
    toc: true
